### ISSUE TITLE
Error during data processing

### ISSUE THREAD

**Issue by N1Knight** [mrniko/netty-socketio#170]
I have this Exception but I dont know what generetad it. 

01:29:58 ERROR Error during data processing. Client sessionId: c9c29ae0-1d4c-447f-8dfa-bed8022d0b04, data: java.lang.NullPointerException.

Do you know why this happens?

**Comment by fcbflying** [comment]
I also got the Exception:
2017-03-16 14:55:10.791 ERROR InPacketHandler:112 - Error during data processing. Client sessionId: a542a0c6-8cd5-4d41-ae7a-48bd4cc40707, data: 
java.lang.NullPointerException: null
        at com.corundumstudio.socketio.JsonSupportWrapper.readAckArgs(JsonSupportWrapper.java:46) ~[goeasy-node.jar:na]

As I found that it caused by there is no related AckCallback with the specified ackId.
So when do the log:
      log.error("Can't read ack args: " + src.readLine() + " for type: " + callback.getResultClass(), e);
NullPointerException will be thrown out.

What confused me , normally when reigster an AckCallback, there will be a debug log:
         log.debug("AckCallback registered with id: {} for client: {}", index, sessionId);

But I can not find this log for the ackId which can not find related AckCallback.

**Comment by bestK** [comment]
Some issue but i fixed. eg:
``` js
 var room = {
      id: '00001',
      name: 'TEST'
    }
    io.emit('create_room', JSON.stringify(room))
    io.on('create_room', function (data) {
      console.log(data)
    })
```

Use  JSON.stringify serialization your data
