### ISSUE TITLE
WebSocket is closed before the connection is established

### ISSUE THREAD

**Issue by HanJY** [mrniko/netty-socketio#187]
Hi there,
i am making chat app using netty-socketio 
tested at web browser... it's perfect wonderful.. 
when i was tested at android(4.3)
at first connect ok.. join ok 
shortly after automatically disconnected...
and android webview logged "WebSocket is closed before the connection is established"
what fault?  i follwed manual 
Is there anyone who knows

**Comment by mrniko** [comment]
Have you resolve your problem?

**Comment by brianlenz** [comment]
I wonder if this is possibly related to the new issue I just put in:

https://github.com/mrniko/netty-socketio/issues/193

We've seen some client disconnects if multiple packets build up in the queue since the queue won't fully flush when you try to send new packets (and there are packets already in the queue).

**Comment by mrniko** [comment]
@HanJY please try it with 1.7.6 version

**Comment by HanJY** [comment]
sorry i am so late.. still logging "websocket is closed before..." 
but work well then update new version(now i use 1.7.6) 
thanks for your comment
