### ISSUE TITLE
1.7.9-10 memory leak ?

### ISSUE THREAD

**Issue by Maypeur** [mrniko/netty-socketio#336]
Hello,
I was using 1.7.8, and after my upgrade to 1.7.10 and a week of use, i see that version 1.7.9 and 1.7.10 have both the same comportement :
- They eat a lot of more memory at start 1.7.9-10 : 263Mo while 1.7.8 : 133Mo.
- 1.7.8 : It run many weeks and memory fluctuates normaly,
1.7.9-10 : With 1000 simultaneous users after 1 hour it reach 1Go in memory and never back down.
Maybe i have to upgrade my code but i do not see any needed change from 1.7.8 to 1.7.9 (i exchange only text messages).
I use version 1.4.5 of socket.io client.
Thanks.

**Comment by mrniko** [comment]
Hi!

I think it's because of `Compression support` feature. It turned on by default. Try to switch off it.

**Comment by Maypeur** [comment]
Hi mrniko,
Thanks for your fast response, i suspected something around that, but do i need to switch it off on server, client or both side ?

**Comment by mrniko** [comment]
It's enough to switch off on server side only

**Comment by Maypeur** [comment]
I disabled http and websocket compression on server side, now it still start with more memory but i let turn the server to see memory fluctuation with users...
I will let you know in a couple of days if it is better.
Thanks.

**Comment by Maypeur** [comment]
You were right ! 
After theses three days i can see that the server processor is a lot more stable and memory usage is normal again. 
But, does it would say that i miss something in my implementation or that there is a trouble in socketio compression side ?
Compression seems to be a great feature, but if it is at the cost of processor usage i prefer eat bandwith ! 
Again, thanks for your help !

**Comment by mrniko** [comment]
> But, does it would say that i miss something in my implementation or that there is a trouble in socketio compression side ?

Socketio uses netty-4.1.0 compression codec. I didn't invent anything :) Maybe memory consumption will be less in next versions.

**Comment by welkinxu** [comment]
@mrniko @Maypeur heres is reason, https://github.com/netty/netty/issues/9803.
The problem is that with compression enabled it will use permessage-deflate with server_no_context_takeover not used. For more infos on what this actual means check:
See https://tools.ietf.org/html/rfc7692#section-7.1.1.1.

So with the configuration we need to create a new Deflater (which is part of the JDK: https://docs.oracle.com/javase/8/docs/api/java/util/zip/Deflater.html ) and keep it "alive" till the connection is closed. The problem here is that Deflater is implemented using JNI and so reserve native memory that will not be released until the connection is closed and so the deflater.end() method can be called by us.

So the only way to "guard" against such a problem is to limit the max number of concurrent connections which use the extension.
