### ISSUE TITLE
Equivalent of io.emit(channel, data) ?

### ISSUE THREAD

**Issue by gholol** [mrniko/netty-socketio#353]
I'm porting a project from nodejs. I have a redis subprocess where I want to process each PMessage. 

    @Override
    public void onPMessage(String pattern, String channel, String message)
    {
        System.out.println("Received new message from the queue on channel " + channel);
				
	 // ???
    }

How I'm supposed to send data only to specified channel/namespace? 

the demos shows only examples of basic server->client and server->all clients operations,'

This is available in the native socket.io library as 

    io.emit(channel, data);

**Comment by whg333** [comment]
for the specified channel, because SocketIOClient bind Netty Channel, I think you can find the specified SocketIOClient instance and use `socketIOClient.sendEvent(event, data)` or `socketIOClient.send(data)`

for the specified namespace, you can see [NamespaceChatLauncher](https://github.com/mrniko/netty-socketio-demo/blob/master/server/src/main/java/com/corundumstudio/socketio/demo/NamespaceChatLauncher.java)
